config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, shallow: true, except: :index
  end

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates :text, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def author_of?(creation)
    id == creation.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[ new create ]
  before_action :load_answer, only: %i[ show edit update destroy ]

  def show
  end

  def edit
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user
    if @answer.save
      redirect_to @question, notice: 'Your answer successfully created.'
      #else
      #redirect_to @question, notice: "Answer can't be blank."
    end

  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      redirect_to question_path(@answer.question)
    else
      redirect_to question_path(@answer.question)
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    puts("+++++++++++++++++")
    params.require(:answer).permit(:text, :correct)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :load_question, only: %i[ show edit destroy ]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end

  end

  def update
    if question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path
    else
      redirect_to question_path
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def load_question
    @question = Question.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.slim
div
  = form_with model: [question, question.answers.new], local: true do |form|
    div
      p
        = form.label :text
        = form.text_area :text
      p
        = form.label :correct
        = form.check_box :correct

    p= form.submit "Add answer"

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render 'shared/nav' %>

  <%= yield %>
  </body>
</html>

app/views/questions/edit.html.slim
=form_with model: question do

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path

- @questions.each do |question|
  p= question.title
  p= question.body
  br

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p= f.submit 'Ask'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body
br
  - if current_user&.author_of?(@question)
    = link_to 'Delete the question', question_path(@question), method: :delete

.answers
  - question.answers.each do |answer|
    div
      = answer.text
      - if current_user.author_of?(answer)
        = link_to 'Delete the answer', answer_path(answer), method: :delete

.answer-errors
  = render 'shared/errors', resource: @answer

= render 'answers/form', question: question

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
span
  - if user_signed_in?
    = "Welcome, #{current_user.email}"
    br
    = link_to 'Logout', destroy_user_session_path, method: :delete
  - else
    = link_to 'sign in', :new_user_session
    br
    = link_to 'registration', :new_user_registration